apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc111
  labels:
    docs-app: wordpress11
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "ceph-rbd"

