apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
  name: gitlab-ci
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims", "secrets", "services", "events", "replicationcontrollers", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "exec"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-ci
  namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: __YOUR_GITLAB_BUILD_NAMESPACE__
roleRef:
  kind: Role
  name: gitlab-ci
  apiGroup: rbac.authorization.k8s.io
