---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-node-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        log
        health 127.0.0.1:50089
        kubernetes cluster.local 234.10.in-addr.arpa 233.10.in-addr.arpa {
          pods insecure
        }
        proxy . 172.26.2.21 172.26.2.22 172.26.2.23
        cache 30
    }

